name: CI Pipeline
run-name: Run API tests

on:
  push:
    branches:
      - main
  
  pull_request:
    branches:
      - main
      
  workflow_dispatch:

env:
  JWT_SECRET: ${{ secrets.JWT_SECRET }}
  PGADMIN_DEFAULT_EMAIL: ${{ secrets.PGADMIN_DEFAULT_EMAIL }}
  PGADMIN_DEFAULT_PASSWORD: ${{ secrets.PGADMIN_DEFAULT_PASSWORD }}
  POSTGRES_PASSWORD: ${{ secrets.PGADMIN_DEFAULT_PASSWORD }}

jobs:
  build_and_run_api_tests:
    name: Build and Run API tests
    timeout-minutes: 60

    strategy:
      matrix:
        tags: ['@users', '@auth']
      fail-fast: false
      
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with: 
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        
    - name: setup and build app server
      run: docker compose -f docker-compose.yml up --build -d

    - name: Wait for server to be ready
      run: |
        timeout=60
        while [ $timeout -gt 0 ]; do
          if curl -f http://localhost:3000 > /dev/null 2>&1; then
            echo "Server is ready"
            break
          fi
          echo "Waiting for server... ($timeout seconds left)"
          sleep 5
          timeout=$((timeout - 5))
        done
        if [ $timeout -le 0 ]; then
          echo "Server failed to start within timeout"
          exit 1
        fi

    - name: 🫙 Cache node modules
      uses: actions/cache@v4
      id: node-modules-cache
      with:
        path: |
          node_modules
        key: modules-${{ hashFiles('package-lock.json') }}

    - name: 📦 Install dependencies
      shell: bash
      run: npm ci
      if: steps.node-modules-cache.outputs.cache-hit != 'true'

    - name: Run API Tests
      id: run-api-tests
      uses: ./.github/actions/run-api-tests
      with:
        tags: ${{ matrix.tags }}

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report-${{ matrix.tags }}
        path: api/playwright-report/
        retention-days: 30
