name: CI Pipeline
run-name: Run API tests

on:
  # push:
  #   branches: main
  # pull_request:
  #   branches: main
  workflow_dispatch:

env:
  JWT_SECRET: ${{ secrets.JWT_SECRET }}
  PGADMIN_DEFAULT_EMAIL: ${{ secrets.PGADMIN_DEFAULT_EMAIL }}
  PGADMIN_DEFAULT_PASSWORD: ${{ secrets.PGADMIN_DEFAULT_PASSWORD }}
  POSTGRES_PASSWORD: ${{ secrets.PGADMIN_DEFAULT_PASSWORD }}

jobs:
  build_and_run_api_tests:
    name: Build and Run API tests
    timeout-minutes: 60

    strategy:
      matrix:
        tags: ['@users', '@auth']
      fail-fast: false
      
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        
    - name: setup and build app server
      run: docker compose -f docker-compose.yml up --build -d

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      run: npx playwright test --grep ${{ matrix.tags }}

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report-${{ matrix.tags }}
        path: playwright-report/
        retention-days: 30
