name: Run API Tests
description: Run API tests Action
inputs:
  tags:
    description: Tags to run
    required: true

runs:
  using: "composite"
  steps:
    - name: 🔧 Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: 🫙 Cache node modules
      uses: actions/cache@v4
      id: node-modules-cache
      with:
        path: |
          node_modules
        key: node-modules-${{ hashFiles('package-lock.json') }}

    - name: 📦 Install dependencies
      shell: bash
      run: npm ci
      if: steps.node-modules-cache.outputs.cache-hit != 'true'

    - name: Get installed Playwright version
      id: playwright-version
      shell: bash
      run: echo "PLAYWRIGHT_VERSION=$(node -e "console.log(require('./package-lock.json').packages[''].devDependencies['@playwright/test'])")" >> $GITHUB_ENV

    - name: Cache playwright binaries
      uses: actions/cache@v4
      id: playwright-cache
      with:
        path: |
          ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}

    - name: 📦🌐 Install Playwright dependencies 
      if: steps.playwright-cache.outputs.cache-hit != 'true'
      shell: bash
      run: npx playwright install --with-deps

    - name: Run API tests
      shell: bash
      run: npx playwright test --grep ${{ inputs.tags }}

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report-${{ inputs.tags }}
        path: api/playwright-report/
        retention-days: 30

    - name: Setup Pages
      uses: actions/configure-pages@v4

    - name: Upload Pages artifact
      uses: actions/upload-pages-artifact@v3
      if: ${{ !cancelled() }}
      with:
        name: playwright-report-${{ inputs.tags }}
        path: api/playwright-report/
        retention-days: 30
        
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
      if: ${{ !cancelled() }}
      with:
        token: ${{ github.token }}
        artifact_name: playwright-report-${{ inputs.tags }}
        path: ${{ inputs.tags }}
